### ISSUE TITLE
Partial put data of referenced documents

### ISSUE THREAD

**Issue by RrOoSsSsOo** [doctrine/mongodb-odm#1291] opened 2015-12-02 10:39 UTC
In my Symfony application I've found a strange bug. I need to find many documents with some field  that are referenced documents but Doctrine put **data of referenced documents** only in some of theme (and the returned documents are different)

In the Contreller I have
```php
foreach($elements as $element)
{
    $object = $objectsRepository->findOneById($element['id']);
}
```

but as result some finded objects are of type `AppBundle\Document\MyType` and other are of type `MongoDBODMProxies\__CG__\AppBundle\Document\MyType`. These last have all field to `null`, except `id`. 

If printed they result:

```php
object(AppBundle\Document\MyType)[1338]
  private 'id' => string '560a1..........................' (length=24)
  private 'name' => string 'Name 1' (length=4)
  private 'description' => string 'Description 1' (length=11)
  ...
object(MongoDBODMProxies\__CG__\AppBundle\Document\MyType)[1405]
  private 'id' (AppBundle\Document\MyType) => string '560a2.....................' (length=24)
  private 'name' (AppBundle\Document\MyType) => null
  private 'description'  (AppBundle\Document\MyType) => null
  ...
```

with `null` value but these fildes **are not null in the originals document**!

But even stranger is the fact that if I add these lines of code into foreach loop to access to the field *name* of referenced document

```php
foreach($elements as $element)
{
    $object = $objectsRepository->findOneById($element['id']);
    if(is_null($object->getReferencedDocumentField()->getName()))
    {
    }
}
```

all fields are returned correctly (always of *MongoDBODMProxies* type)

```php
object(AppBundle\Document\MyType)[1338]
  private 'id' => string '560a1..........................' (length=24)
  private 'name' => string 'Name 1' (length=4)
  private 'description' => string 'Description 1' (length=11)
  ...
object(MongoDBODMProxies\__CG__\AppBundle\Document\MyType)[1405]
  private 'id' (AppBundle\Document\MyType) => string '560a2.....................' (length=24)
  private 'name' (AppBundle\Document\MyType) => string 'Name 2' (length=4)
  private 'description'  (AppBundle\Document\MyType) => string 'Description 2' (length=11)
  ...
```

Thanks for your help

PS: Symfony components versions
* **mongodb-odm** v1.0.x-dev
* **mongodb-odm-bundle** v3.0.x-dev

**Comment by alcaeus** [comment] 2015-12-02 12:58
The "empty" documents are placeholders that have no data loaded into them for performance reasons. Once you first access a method in that object, the entire object is fetched from the database and then hydrated into your object. As you noted yourself, the data is correctly stored in the database, it's just not loaded until you need it.

Closing as not a bug - if you have further questions please consider asking them on StackOverflow or other support channels.

**Closed by alcaeus** 2015-12-02 12:58 UTC
Labels: question
