### ISSUE TITLE
 Cannot assign string to property of type MongoDB\BSON\ObjectIdInterface

### ISSUE THREAD

**Issue by smilesrg** [doctrine/mongodb-odm#2339] opened 2021-07-11 13:43 UTC
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 4.3

#### Summary

I'm trying to use ObjectId in the embedded document. But got an error while dehydrating object:

```
There were 2 errors:

1) App\Tests\Functional\Controller\HotelsControllerTest::testGetHotelsCollection
TypeError: Cannot assign string to property App\Document\HotelRoom::$hotelRoomId of type MongoDB\BSON\ObjectIdInterface

/extranet/vendor/doctrine/persistence/lib/Doctrine/Persistence/Reflection/TypedNoDefaultReflectionProperty.php:56
/extranet/var/cache/test/doctrine/odm/mongodb/Hydrators/AppDocumentHotelRoomHydrator.php:41
/extranet/vendor/doctrine/mongodb-odm/lib/Doctrine/ODM/MongoDB/Hydrator/HydratorFactory.php:496
/extranet/vendor/doctrine/mongodb-odm/lib/Doctrine/ODM/MongoDB/Persisters/DocumentPersister.php:689
/extranet/vendor/doctrine/mongodb-odm/lib/Doctrine/ODM/MongoDB/Persisters/DocumentPersister.php:646
/extranet/vendor/doctrine/mongodb-odm/lib/Doctrine/ODM/MongoDB/UnitOfWork.php:2707
/extranet/vendor/doctrine/mongodb-odm/lib/Doctrine/ODM/MongoDB/PersistentCollection/PersistentCollectionTrait.php:143
/extranet/vendor/doctrine/mongodb-odm/lib/Doctrine/ODM/MongoDB/PersistentCollection/PersistentCollectionTrait.php:494
/extranet/vendor/symfony/serializer/Serializer.php:167
/extranet/vendor/symfony/serializer/Normalizer/AbstractObjectNormalizer.php:203
/extranet/vendor/symfony/serializer/Serializer.php:154
/extranet/vendor/symfony/serializer/Serializer.php:168
/extranet/vendor/symfony/serializer/Serializer.php:127
/extranet/vendor/friendsofsymfony/rest-bundle/Serializer/SymfonySerializerAdapter.php:38
/extranet/vendor/friendsofsymfony/rest-bundle/View/ViewHandler.php:265
/extranet/vendor/friendsofsymfony/rest-bundle/View/ViewHandler.php:190
/extranet/vendor/friendsofsymfony/rest-bundle/View/ViewHandler.php:158
/extranet/vendor/friendsofsymfony/rest-bundle/EventListener/ViewResponseListener.php:84
/extranet/vendor/symfony/event-dispatcher/EventDispatcher.php:270
/extranet/vendor/symfony/event-dispatcher/EventDispatcher.php:230
/extranet/vendor/symfony/event-dispatcher/EventDispatcher.php:59
/extranet/vendor/symfony/http-kernel/HttpKernel.php:162
/extranet/vendor/symfony/http-kernel/HttpKernel.php:79
/extranet/vendor/symfony/http-kernel/Kernel.php:195
/extranet/vendor/symfony/http-kernel/HttpKernelBrowser.php:63
/extranet/vendor/symfony/framework-bundle/KernelBrowser.php:159
/extranet/vendor/symfony/browser-kit/AbstractBrowser.php:384
/extranet/vendor/symfony/browser-kit/AbstractBrowser.php:158
/extranet/tests/Functional/Controller/HotelsControllerTest.php:41

2) App\Tests\Functional\Controller\HotelsControllerTest::testHotelRoomCreate
TypeError: Cannot assign string to property App\Document\HotelRoom::$hotelRoomId of type MongoDB\BSON\ObjectIdInterface

/extranet/vendor/doctrine/persistence/lib/Doctrine/Persistence/Reflection/TypedNoDefaultReflectionProperty.php:56
/extranet/vendor/doctrine/mongodb-odm/lib/Doctrine/ODM/MongoDB/Mapping/ClassMetadata.php:1453
/extranet/vendor/doctrine/mongodb-odm/lib/Doctrine/ODM/MongoDB/UnitOfWork.php:1076
/extranet/vendor/doctrine/mongodb-odm/lib/Doctrine/ODM/MongoDB/UnitOfWork.php:1670
/extranet/vendor/doctrine/mongodb-odm/lib/Doctrine/ODM/MongoDB/UnitOfWork.php:2173
/extranet/vendor/doctrine/mongodb-odm/lib/Doctrine/ODM/MongoDB/UnitOfWork.php:1689
/extranet/vendor/doctrine/mongodb-odm/lib/Doctrine/ODM/MongoDB/UnitOfWork.php:1627
/extranet/vendor/doctrine/mongodb-odm/lib/Doctrine/ODM/MongoDB/DocumentManager.php:458
/extranet/src/Repository/AbstractRepository.php:11
/extranet/src/Repository/AbstractRepository.php:26
/extranet/src/Controller/HotelRoomsController.php:43
/extranet/vendor/symfony/http-kernel/HttpKernel.php:157
/extranet/vendor/symfony/http-kernel/HttpKernel.php:79
/extranet/vendor/symfony/http-kernel/Kernel.php:195
/extranet/vendor/symfony/http-kernel/HttpKernelBrowser.php:63
/extranet/vendor/symfony/framework-bundle/KernelBrowser.php:159
/extranet/vendor/symfony/browser-kit/AbstractBrowser.php:384
/extranet/vendor/symfony/browser-kit/AbstractBrowser.php:158
/extranet/tests/Functional/Controller/HotelsControllerTest.php:88


``` 

classes:

```php
<?php

namespace App\Document;

use Doctrine\Common\Collections\Collection;
use Doctrine\ODM\MongoDB\Mapping\Annotations as ODM;

/**
 * @ODM\Document
 */
class Hotel
{
   /// ...
    /**
     * @var HotelRoom[]
     *
     * @ODM\EmbedMany(targetDocument=HotelRoom::class)
     */
    protected iterable|Collection $hotelRooms;
}
```

```php
<?php

namespace App\Document;

use Doctrine\ODM\MongoDB\Mapping\Annotations as ODM;
use MongoDB\BSON\ObjectIdInterface;

/**
 * @ODM\EmbeddedDocument
 */
class HotelRoom
{
    /**
     * @ODM\Id
     */
    protected ObjectIdInterface $hotelRoomId;
    
    // ...
    
    public function getHotelRoomId(): ObjectIdInterface
    {
        return $this->hotelRoomId;
    }

    public function setHotelRoomId(ObjectIdInterface $hotelRoomId): HotelRoom
    {
        $this->hotelRoomId = $hotelRoomId;

        return $this;
    }
}
```

#### Current behavior

Probably it tries assign string value to the typehinted with `ObjectIdInterface` property.

#### How to reproduce
1. Create parent and embedded document
2. Create `@ODM\Id` property and typehint it as `\MongoDB\BSON\ObjectIdInterface`
3. Try to get the object from the database.

#### Expected behavior

No exceptions.

**Comment by malarzm** [comment] 2021-07-11 23:12
@smilesrg thanks for the report! Could you please try reproduce your case as a failing test case and make a PR with it? You can take a page from our other functional tests: https://github.com/doctrine/mongodb-odm/blob/2.2.x/tests/Doctrine/ODM/MongoDB/Tests/Functional/Ticket/GH2157Test.php

**Comment by IonBazan** [comment] 2021-09-07 07:33
@smilesrg This is because `IdType` converts `ObjectId` objects into `string` during hydration and this is expected behaviour as it decouples your document from internal persistence classes: https://github.com/doctrine/mongodb-odm/blob/2.2.x/lib/Doctrine/ODM/MongoDB/Types/IdType.php.
I would suggest typing your property as `string` instead. Another option would be to use `custom_id` field type (`@ODM\Id(type="custom_id")`) or creating a custom type that ensures the hydrated object is an `ObjectId`.

I could imagine an use case where you want to keep it as `ObjectId` in your document class - maybe we could introduce an option to map the documents as such: `@ODM\Id(storeAs="ObjectId")`.

**Comment by alcaeus** [comment] 2023-01-18 13:20
Closing: as noted by @IonBazan this is not a bug, but rather intended. If you want to avoid using a string in your document for the default ID, use the `custom_id` type, which does not do any value transformation.

As for the suggestion of using `storeAs`, we've usually used this to indicate how something should be stored in the database (mainly for references). I would not want to use the same option to also specify how something should be stored in the object itself but rather use the type system for this (as we should've done in the first place).

**Closed as not planned by alcaeus** 2023-01-18 13:20 UTC
