### ISSUE TITLE
Superfluous $unset query when using "set" collection strategy 

### ISSUE THREAD

**Issue by seb0zz** [doctrine/mongodb-odm#1011] opened 2015-01-13 17:25 UTC
Hi,

I am using the Symfony2 bundle I have a document which has some embedded documents. For that I use the EmbedMany annotation with the collection strategy "set". The strange thing is that every time I update this field of the document Doctrine automatically triggers an $unset query before the query that contains the "$set". 

It doesn't seem to be a problem with the Symfony2 bundle.

Does this have a reason or is it a bug?

**Comment by malarzm** [comment] 2015-01-15 11:23
I can confirm this is happening but I think that problem is elsewhere, consider this passing test:

```
<?php

namespace Doctrine\ODM\MongoDB\Tests\Functional\Ticket;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ODM\MongoDB\Mapping\Annotations as ODM;

class GH1011Test extends \Doctrine\ODM\MongoDB\Tests\BaseTest
{
    public function testSchedulingCollections()
    {
        $doc = new GH1011Documnet();
        $doc->embeds->add(new GH1011Embedded('test1'));
        $this->dm->persist($doc);
        $this->dm->flush();
        $this->dm->clear();
        $test = $this->dm->getRepository(get_class($doc))->find($doc->id);
        $test->embeds->add(new GH1011Embedded('test2'));
        $this->uow->computeChangeSets();
        $this->assertTrue($this->uow->isCollectionScheduledForUpdate($test->embeds));
        $this->assertFalse($this->uow->isCollectionScheduledForDeletion($test->embeds));
    }
}

/** @ODM\Document */
class GH1011Documnet
{
    /** @ODM\Id */
    public $id;

    /** @ODM\EmbedMany(targetDocument="GH1011Embedded") */
    public $embeds;

    public function __construct()
    {
        $this->embeds = new ArrayCollection();
    }
}

/** @ODM\EmbeddedDocument */
class GH1011Embedded
{
    /** @ODM\String */
    public $name;
    
    public function __construct($name)
    {
        $this->name = $name;
    }
}
```

``CollectionPersister::delete`` which triggers ``$unset`` is ran by ``UoW`` only if collection is scheduled for deletion.

In my case the updated field was manipulated by Symfony's Form component so I think that it could change entire ``PersistentCollection`` instead of modifying it element by element which results in ``UoW`` scheduling "old" collection for removal (``$unset``) since it's not same object ``UoW`` knows about and later it schedules new one for update (``$set``). Unfortunately I don't have enough time to dig deeper and see if I'm right or not about the Form being source of the issue.

**Comment by seb0zz** [comment] 2015-01-15 14:04
Thanks for your research. I will reopen the issue for the Symfony bundle so that they can take a look at this issue.

**Comment by malarzm** [comment] 2015-01-15 14:31
Actually I'm not sure if its Form component itself - I've just checked another piece of code manipulating my data with Form and ``$unset`` is not triggered there while updating ``@EmbedMany`` field - possibly in place I've checked before I had some additional logic and I was the one manipulating ``PersistentCollection`` in some wrong way.

**Comment by malarzm** [comment] 2015-05-20 11:48
We decided that this is indeed a bug and should be solved. Marking it for milestone and will come back to the issue soon

**Comment by seb0zz** [comment] 2015-05-20 12:01
:+1:

**Comment by malarzm** [comment] 2015-06-11 22:04
#1120 was merged manually in https://github.com/doctrine/mongodb-odm/commit/c06e8d40a3fd77a9c24481247890863ea858355c

**Closed by malarzm** 2015-06-11 22:04 UTC
Labels: bug, has PR
