### ISSUE TITLE
Undefined index: C:7:"MongoId":24:{58c72404911e696c6bf5b970}

### ISSUE THREAD

**Issue by nationdata-it** [doctrine/mongodb-odm#1589] opened 2017-05-11 23:46 UTC
Selecting my collection job and jobs has reference many with employees, when i'm selecting the jobs and job employees it comes up with this error.

/vendor/doctrine/mongodb-odm/lib/Doctrine/ODM/MongoDB/UnitOfWork.php

ENV:
PHP 5.5.9
ODM: 1.0.8

**Comment by alcaeus** [comment] 2017-05-12 05:27
Please share some code that helps us reproduce the problem, ideally in form of a failing test case.

As a note, you are using MongoDB ODM 1.0 which we don't support anymore. Please upgrade to 1.1 and let us know if the issue persists. Thank you!

**Comment by nationdata-it** [comment] 2017-05-18 02:02
Thanks @alcaeus thanks for your response.

here is my document and code hopefully it will be helpful to elaborate the problem.

jobs document looks like
`{
    "_id" : ObjectId("58a67fd0911e69a0298b4568"),
    "record_status" : "Open",
    "title" : "dfdfdf dfd f",
    "description" : " dfdf",
    "note" : "dfdf",
    "employees" : [ 
        ObjectId("5858b7f4911e69283b8b81ff"),
       ObjectId("57b6a469911e693e3a8b4568")
    ]
}`

employee collection looks like
`{
    "_id" : ObjectId("5858b7f4911e69283b8b81ff"),
    "record_status" : "active",
    "generated_timestamp" : ISODate("2016-08-19T06:17:13.000Z"),
    "salutation" : "Mr.",
    "firstname" : "B",
    "lastname" : "Admin1",
    "username" : "user1",
    "email" : "email@email.com",
    "has_verified" : false,
    "user_type" : "normal_user",
    "employee_id" : "0001",
    "last_login_timestamp" : ISODate("2017-05-17T02:08:48.000Z"),
    "vehicle" : null
},
{
    "_id" : ObjectId("57b6a469911e693e3a8b4568"),
    "record_status" : "active",
    "generated_timestamp" : ISODate("2016-08-19T06:17:13.000Z"),
    "salutation" : "Mr.",
    "firstname" : "A",
    "lastname" : "Admin2",
    "username" : "user2",
    "email" : "email1@email.com",
    "has_verified" : false,
    "user_type" : "normal_user",
    "employee_id" : "0002",
    "last_login_timestamp" : ISODate("2017-05-17T02:08:48.000Z"),
    "vehicle" : null
}`

code is:
`$employee_id = "57b6a469911e693e3a8b4568";
		$jobs = $dm->createQueryBuilder("Jobs")
				->field("record_status")
				->equals("open")
				->getQuery()
				-> execute();
		foreach ($jobs as $job) {
			//when i execute the bellow statement the above error is appeared.
			if(!empty($job->getEmployeeIDs()) && in_array($employee_id, $job->getEmployeeIDs())){
			}
		}
`

Job Class:
`<?php

/** @ODM\Document (collection="jobs") */
class Job
{

	const open = 'Open';
	const scheduled = 'Scheduled';
	const cancelled = 'Cancelled';
	const started = 'Started';
	const ended = 'Ended';

	/** @ODM\Id */
	public $id;

	/** @ODM\Field(type="string") */
	public $record_status;

	/** @ODM\Field(type="string") */
	public $title;

	/** @ODM\Field(type="string") */
	public $description;

	/** @ODM\Field(type="string") */
	public $note;

	/** @ODM\ReferenceMany(targetDocument="Employee", simple=true) */
	private $employees;

	public function __construct()
	{
		$this->employees = new ArrayCollection();
	}


	public function getEmployeeIDs()
	{

		$employee_ids = [];
		foreach ($this->employees as $record_employee) {
			if (!in_array($record_employee->id, $employee_ids)) {
				$employee_ids[] = $record_employee->getId();
			}
		}
		return $employee_ids;
	}

}

`

**Comment by malarzm** [comment] 2017-05-18 07:59
@nationdata-it I don't see anything weird in your code, could you please write a failing test case like [this one](https://github.com/doctrine/mongodb-odm/blob/68d4774c09de387a70dc492951f6e38df80ff092/tests/Doctrine/ODM/MongoDB/Tests/Functional/Ticket/GH1572Test.php) (or any other from that directory)?

**Comment by malarzm** [comment] 2017-06-13 21:15
Closing because of no update from OP. @nationdata-it feel free to either re-open this issue with more details or better yet, provide a failing test case.

**Closed by malarzm** 2017-06-13 21:15 UTC
Labels: question

**Comment by nationdata-it** [comment] 2018-01-12 12:09
Found cause for this issue.

One of my collection was using wrong annotation reference.
It was using employee model name but it was Employee.

Originally it was
/** @ODM\ReferenceMany(targetDocument="employee", simple=true) */
private $employees;

so when proxies are generated it was creating class name with proxies... employee and it was actually looking for proxies..Employee.

changed to this
/** @ODM\ReferenceMany(targetDocument="Employee", simple=true) */
private $employees;

and worked fine for me.

Sorry for late update, hopefully this explains better.
