### ISSUE TITLE
Discriminator value is lost for reloaded documents

### ISSUE THREAD

**Issue by josefsabl** [doctrine/mongodb-odm#2015] opened 2019-04-23 16:21 UTC
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     | dev-master

#### Summary

Okay, so this is probably related or maybe duplicate to: https://github.com/doctrine/mongodb-odm/issues/2002

But not only I get the error message described in the ticket but I also lose the discriminator value for the references associations.

#### Current behavior

After reloading and setting new value for reference, the discriminator field in the ref is lost.

Setting discriminator map will fix the problem.

#### How to reproduce

https://github.com/doctrine/mongodb-odm/pull/2016

![2019-04-23_18h24_27](https://user-images.githubusercontent.com/1252386/56598695-47f2d400-65f5-11e9-9e3a-38065c184135.png)

**Comment by josefsabl** [comment] 2019-04-23 16:52
If I may humbly present my opinion. I don't like the discriminator map feature at all. Especially with the latest changes.

I believe it violates DRY and OCP quite obviously.

First of all I need to maintain lists like:

```
user => Document\User
userAdmin => Document\UserAdmin
userBfu => Document\UserBfu
userSuper => Document\UserSuper
...
```

We also search for documents by their type (`findBy(['class' => Document\User])`). And as we don't want to have string constants in the code we would have to create constants for strings like `user`, `userAdmin` etc... and they cannot be used in annotations afaik. So there is no way to solve ideally.

But more importantly, I need to add to this list each time any other developer adds a new class in his package that is merely dependent on the base package.

The latest change with the exception targets the later problem so that the user does not forget. But it is not only about forgetting but about architecture. Imagine you have installed the base class as a dependency, think of it as some company level framework.

I know about the argument that the implementation details should not leak into the database and not using a discriminator map prevents the code to be refactored (inability to move/rename classes). Well, I'd put aside the fact that I could just run a trivial script to update the database, but the discriminator map was useful for migration as well. I could rename the class and add the new name to the discriminator map, think of alsoLoad. It is impossible with the introduction of the exception.

Thanks for listening, or not :-)

**Comment by malarzm** [comment] 2019-04-23 18:10
I'll allow myself to answer to some of your points:

> We also search for documents by their type (findBy(['class' => Document\User])).

You shouldn't need to query by a discriminator field, if you get a repository for a specific class (say `Document\User`) it'll automatically get you instances of that class only. Discriminator and its value are ODM-specific, it shouldn't leak to your code.

> And as we don't want to have string constants [...] and they cannot be used in annotations afaik.

Both consts and the `::class` "const" can be used with annotations: https://github.com/doctrine/mongodb-odm/blob/485d84dc05401aea58db9d41335924475b50f7f1/tests/Documents/CmsUser.php#L27

> Imagine you have installed the base class as a dependency, think of it as some company level framework.

I'd say that such class should not be mapped as a document, `MappedSuperclass` would be a better fit perhaps?

>  I could rename the class and add the new name to the discriminator map, think of alsoLoad. It is much less useful for this purpose with the introduction of the exception.

I'm not sure I follow here, you still can add an entry to the discriminator map and it will work? We're just throwing an exception when a class is missing there, not when an extra one is found.

**Comment by josefsabl** [comment] 2019-04-24 09:50
Thank you for your reply! Not all my concerns are resolved but it was inspirational nonetheless :-)

> I'm not sure I follow here, you still can add an entry to the discriminator map and it will work? We're just throwing an exception when a class is missing there, not when an extra one is found.

I thought I would only add value to the discriminator map if the class was renamed and leave the default behaviour with class name as discriminator value when not in discriminator map. But I may be mistaken, I was merely theorizing :-)

Cheers.

**Comment by josefsabl** [comment] 2019-04-25 07:52
The theoretical debate aside :-) Is this a bug? Is it a duplicate for #2002 or am I missing something?

**Comment by alcaeus** [comment] 2019-04-26 14:36
I'm currently checking it against the fix I made for #2002. Not quite sure what it is just yet 😉

**Comment by alcaeus** [comment] 2019-04-28 10:58
While I could reproduce it in master, I couldn't reproduce it with the fixes from #2005 applied. With that in mind, I'd like to finish #2005 and get that merged down to master and revisit this afterwards. I believe you may just be seeing different effects of the same bug.

**Comment by alcaeus** [comment] 2019-04-28 11:39
With the test case provided in #2016, I could not reproduce any failures, neither by leaving the `exit` call in, nor by removing it. I'm closing this - please reopen if you feel that I've missed something.

**Closed by alcaeus** 2019-04-28 11:39 UTC

**Comment by josefsabl** [comment] 2019-04-29 11:25
The exception went away, but new problem appeared. See: #2024
