### ISSUE TITLE
Aggregation : Add the ability to directly use $expr in Match stage

### ISSUE THREAD

**Issue by aturcey** [doctrine/mongodb-odm#1907] opened 2018-11-29 15:53 UTC
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | yes/no
| BC Break    | yes/no

#### Summary

The following code : 

```php
/** AggregationBuilder **/
$ab->match()
            ->expr(
                $ab->expr()->eq('$totalCount', '$expectedCount')
            );
```
Generates an empty $match like this : 
db.books.aggregate([ { "$match": [ ] } ], { "cursor": true });

As a **workaround** we can get the pipeline from builder and manually edit before aggregate using : 
```php
$collection->aggregate($pipeline, ['cursor' => true]);
```
Thanks to @alcaeus

**Comment by alcaeus** [comment] 2019-10-08 13:23
Duplicate of #1824.

**Closed by alcaeus** 2019-10-08 13:23 UTC
