### ISSUE TITLE
not found cache\prod/doctrine/odm/mongodb/Hydrators\AppDocumentUserHydrator.php

### ISSUE THREAD

**Issue by hectorprats** [doctrine/mongodb-odm#1744] opened 2018-02-20 02:53 UTC
Fatal error: require(): Failed opening required 'XXX\var\cache\prod/doctrine/odm/mongodb/Hydrators\AppDocumentUserHydrator.php' (include_path='.;C:\php\pear') in XXX\vendor\doctrine\mongodb-odm\lib\Doctrine\ODM\MongoDB\Hydrator\HydratorFactory.php on line 142

why? I tried everything.. It works in debug mode, but no in prod mode.

**Comment by mrohnstock** [comment] 2018-02-20 07:57
You missed to warmup the hydratorcache for prod.

Should by something like this:

```
php bin/console doctrine:mongodb:generate:hydrators --env=prod
```

**Comment by malarzm** [comment] 2018-02-20 09:03
Also you seem to have "/" and "\" mixed in the path, you may want to check if path to the cache folder is correct.

**Comment by malarzm** [comment] 2018-03-14 16:22
Closing as there's no new activity and to me the question seems to be answered.

**Closed by malarzm** 2018-03-14 16:22 UTC
Labels: question

**Comment by aknowicki** [comment] 2021-04-30 08:27
@malarzm 

There's still a problem:
[2021-01-20 06:23:08] php.CRITICAL: Fatal Compile Error: require(): Failed opening required '/var/app/current/var/cache/prod/doctrine/odm/mongodb/Hydrators/CollageBundleClientBundleDocumentApplicationHydrator.php' (include_path='.:/usr/share/pear7:/usr/share/php') {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Compile Error: require(): Failed opening required '/var/app/current/var/cache/prod/doctrine/odm/mongodb/Hydrators/CollageBundleClientBundleDocumentApplicationHydrator.php' (include_path='.:/usr/share/pear7:/usr/share/php') at /var/app/current/vendor/doctrine/mongodb-odm/lib/Doctrine/ODM/MongoDB/Hydrator/HydratorFactory.php:134)"} []

It occur occasionally and persist till you clear cache or regenerate hydrators. After a while it starts over.

note:
The file exist and has correct permissions.

**Comment by malarzm** [comment] 2021-04-30 12:19
> The file exist and has correct permissions.

That would mean the `require` call is broken and it's not ODM's fault :) If the error goes away after a moment it might be as well a delay between docker and your local filesystem, or whatever else.

Offhand, glad to see Collage is still alive ^^

**Comment by aknowicki** [comment] 2021-04-30 23:04
I thought about the delay from the system, but production is on AWS. 
Instances are pretty powerful so I doubt it. 

Yeah Collage still alive :)

**Comment by Steveb-p** [comment] 2021-05-01 10:42
I've had a similar issue on a production environment before (unrelated to ODM itself). I've had two possible causes:
1. I was `mv`-ing the instances around.
2. I had a symlink-based installation and my nginx passed to php-fpm 
```
fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
```
which caused my php-fpm to share cache between instances. What helped me was:
```
fastcgi_param  SCRIPT_FILENAME  $realpath_root$fastcgi_script_name;
```

And in my case it was the cause for errors on instance switch.

This might be completely unrelated to what you're having, but maybe it will point you in the right direction...? Because as malarzm said, this looks like just PHP failing to load an existing file.
