### ISSUE TITLE
Compatibility issue with mongo-php-library v1.2

### ISSUE THREAD

**Issue by olvlvl** [doctrine/mongodb-odm#1737] opened 2018-01-13 15:57 UTC
Hi,

It seems `mongodb-odm` v1.1.7 as a compatibility issue with `mongo-php-library` v1.2:

```
"Call to undefined method MongoDB\Driver\WriteConcern::isDefault()" at
/server/http/vendor/mongodb/mongodb/src/Operation/DropCollection.php:72
/server/http/vendor/mongodb/mongodb/src/Collection.php:431
/server/http/vendor/alcaeus/mongo-php-adapter/lib/Mongo/MongoCollection.php:247
/server/http/vendor/doctrine/mongodb/lib/Doctrine/MongoDB/Collection.php:1102
/server/http/vendor/doctrine/mongodb/lib/Doctrine/MongoDB/Collection.php:297
/server/http/vendor/doctrine/mongodb-odm/lib/Doctrine/ODM/MongoDB/SchemaManager.php:373
/server/http/vendor/doctrine/mongodb-odm/lib/Doctrine/ODM/MongoDB/SchemaManager.php:357
```

Everything is fine with `mongo-php-library` v1.1.2. Should we have a `mongodb-odm` v1.1.8 with tighter restrictions?

I'm not sure what's causing the error so I opened an issue on `mongodb/mongo-php-library` https://github.com/mongodb/mongo-php-library/issues/455.

**Comment by alcaeus** [comment] 2018-01-13 16:13
There will not be a 1.1.8 release as 1.1 is no longer supported. This issue is caused by mongo-php-library, so the second issue you created is in the right place. Closing here.

**Closed by alcaeus** 2018-01-13 16:13 UTC
