### ISSUE TITLE
InvalidArgumentException: Invalid type specified "json".

### ISSUE THREAD

**Issue by oroshnivskyy** [doctrine/mongodb-odm#407] opened 2012-09-15 10:24 UTC
Installed this extension and got exception:
InvalidArgumentException: Invalid type specified "json".

    in /home/oleg/projects/mlm/vendor/doctrine-mongodb-odm/lib/Doctrine/ODM/MongoDB/Mapping/Types/Type.php line 119
    at Type::getType() in /home/oleg/projects/mlm/vendor/doctrine-mongodb-odm/lib/Doctrine/ODM/MongoDB/Hydrator/HydratorFactory.php line 222
    at HydratorFactory->generateHydratorClass() in /home/oleg/projects/mlm/vendor/doctrine-mongodb-odm/lib/Doctrine/ODM/MongoDB/Hydrator/HydratorFactory.php line 165
    at HydratorFactory->generateHydratorClasses() in /home/oleg/projects/mlm/vendor/bundles/Symfony/Bundle/DoctrineMongoDBBundle/CacheWarmer/HydratorCacheWarmer.php line 73
    at HydratorCacheWarmer->warmUp() in /home/oleg/projects/mlm/vendor/symfony/src/Symfony/Component/HttpKernel/CacheWarmer/CacheWarmerAggregate.php line 47
    at CacheWarmerAggregate->warmUp() in /home/oleg/projects/mlm/app/bootstrap.php.cache line 795
    at Kernel->initializeContainer() in /home/oleg/projects/mlm/app/bootstrap.php.cache line 517
    at Kernel->boot() in /home/oleg/projects/mlm/app/bootstrap.php.cache line 548
    at Kernel->handle() in /home/oleg/projects/mlm/hippl.net/app_dev.php line 25

**Comment by malarzm** [comment] 2015-06-08 20:50
Closing the issue since it references BETA5 and no steps to reproduce were given. @oroshnivskyy please reopen the issue if you would have more informations

**Closed by malarzm** 2015-06-08 20:50 UTC
